import { NextResponse } from "next/server";

const museumSignals = [
  "미술관", "박물관", "갤러리", "museum", "gallery", "메트로폴리탄",
  "메트", "루브르", "오르세", "테이트", "구겐하임", "모마", "moma",
  "휘트니", "국립중앙", "국립현대", "리움", "호암", "아모레퍼시픽",
  "서울시립", "대림", "뮤지엄", "아트센터", "우피치", "프라도",
];

const genericOnly = /^(온라인|인터넷|웹|거기|여기|그곳|갤러리|미술관|박물관)/i;
const discoveryIntent = /(알려\s*줘|추천|어디|목록|리스트|찾아\s*줘|가능한\s*(미술관|박물관|갤러리)|볼\s*수\s*있는|갈\s*만한)/i;

const SYSTEM_INSTRUCTIONS = `You are a world-class museum curator and a Sotheby's auction specialist. The evidence supplied to this application comes from museum and cultural-institution APIs and FAQs worldwide, together with official sources retrieved for the user's question. Base every answer strictly and explicitly on the evidence provided in the current request. Use no unsupported knowledge, assumptions, or invented details.

You must follow these rules:
1. Explain only information that exists in the supplied or retrieved evidence. If the evidence does not contain the answer, say so plainly and do not fill the gap from general knowledge.
2. For every important factual explanation, politely recommend confirmation with the relevant museum or institution. When an official contact page, telephone number, or email address is present in the evidence, provide it; never invent contact details.
3. Never infer or guess a person's identity, gender, emotions, age, intent, or purpose.
4. Never infer causes of behavior or causal relationships between events.
5. Do not exaggerate, embellish, or overstate descriptions generated by the model used at https://customer-auto-eight.vercel.app/ . Clearly distinguish directly verified facts from model-generated descriptions.
6. Use a gentle, careful, courteous, and humble tone. Museum visitors may be discerning and sensitive, so avoid patronizing, confrontational, or overly confident language.
7. If producing a complete answer will take a long time, present the first verified search result as a clearly labeled preliminary finding, then continue with the remaining verification.
8. Never fabricate an answer when the required data is absent. Say that the information could not be verified, offer a sincere apology, provide an official contact route when verified, and suggest a practical alternative.
9. Keep the answer as concise and objective as possible.
10. Provide every answer in this order: Korean, English, French, and Simplified Chinese. Keep the factual meaning and degree of uncertainty identical in all four versions.
11. Use plain text only. Never output Markdown heading or emphasis characters. In particular, the characters # and * must not appear anywhere in the answer.

Verification procedure:
- Search broadly, but treat only official museum, cultural-institution, government, official ticketing, and official collection sources as evidence.
- For a named institution, check its visitor information, FAQ, policy or regulations, online collection, virtual tour, press release, official ticketing, and Contact pages as relevant.
- Prefer the most recent official information and state the verification date when available.
- For online-viewing questions, verify separately whether an official online collection, virtual tour, exhibition video, or official Google Arts & Culture institutional page exists.
- Use only links, policy names, operating hours, telephone numbers, and email addresses actually present in the evidence.

Answer structure in each of the four languages:
- Begin with one of: Yes; No; Partly; or Not verified.
- Briefly state what is and is not supported by the evidence.
- Give the official rule or guidance, source, and verification date when available.
- Provide concise steps the user can take.
- Recommend confirmation with the relevant institution for every important factual point.
- If not verified, sincerely apologize, provide verified official contact information if available, and offer one to three practical alternatives.
- For recommendation or list questions, provide about five verified institutions when appropriate, each as: institution — available method — how to access it — official link.
- Never make a statement stronger than its supporting evidence.`;

function needsMuseumName(question: string) {
  const normalized = question.toLowerCase();
  if (discoveryIntent.test(normalized)) return false;
  const hasKnownSignal = museumSignals.some((signal) => normalized.includes(signal));
  return !hasKnownSignal || genericOnly.test(normalized);
}

export async function POST(request: Request) {
  let question = "";
  try {
    const body = (await request.json()) as { question?: unknown };
    question = typeof body.question === "string" ? body.question.trim() : "";
  } catch {
    return NextResponse.json({ error: "질문 형식을 확인해 주세요." }, { status: 400 });
  }

  if (!question) {
    return NextResponse.json({ error: "질문을 입력해 주세요." }, { status: 400 });
  }

  if (question.length > 500) {
    return NextResponse.json({ error: "질문은 500자 이내로 입력해 주세요." }, { status: 400 });
  }

  if (needsMuseumName(question)) {
    return NextResponse.json({
      answer:
        "한국어 — 확인되지 않습니다. 정확한 미술관을 특정하지 못해 진심으로 죄송합니다. 온라인 관람, 입장료, 촬영 규정과 연락처는 기관과 지점마다 다르므로 해당 기관에 확인하시기를 권합니다. 미술관의 정확한 이름과 도시를 알려주시면 공식 규정·FAQ·온라인 컬렉션·문의 페이지에 근거해 확인하겠습니다.\n\nEnglish — Not verified. I sincerely apologize, but the museum cannot be identified from the question. Online viewing, admission, photography rules, and contact details vary by institution and branch, so confirmation with the institution is recommended. Please provide the museum's exact name and city so I can check its official policies, FAQ, online collection, and contact page.\n\nFrançais — Non vérifié. Je vous prie sincèrement de m’excuser, mais la question ne permet pas d’identifier précisément le musée. La visite en ligne, les tarifs, les règles photographiques et les coordonnées varient selon l’établissement et le site ; une confirmation auprès de l’établissement est donc recommandée. Indiquez le nom exact du musée et la ville afin que je puisse consulter ses règles officielles, sa FAQ, sa collection en ligne et sa page de contact.\n\n简体中文 — 未核实。非常抱歉，仅凭当前问题无法确定具体的博物馆。在线参观、票价、摄影规定和联系方式会因机构及分馆而异，建议向相关机构确认。请提供博物馆的准确名称和所在城市，我将依据其官方规定、常见问题、在线馆藏和联系页面进行核实。",
    });
  }

  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) {
    return NextResponse.json(
      { error: "답변 서비스 설정이 아직 완료되지 않았습니다." },
      { status: 503 },
    );
  }

  try {
    const openAIResponse = await fetch("https://api.openai.com/v1/responses", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${apiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "gpt-5.6-luna",
        instructions: SYSTEM_INSTRUCTIONS,
        input: question,
        tools: [{ type: "web_search", search_context_size: "high" }],
        reasoning: { effort: "low" },
        max_output_tokens: 4000,
      }),
    });

    if (!openAIResponse.ok) {
      const requestId = openAIResponse.headers.get("x-request-id");
      console.error("OpenAI request failed", openAIResponse.status, requestId);
      return NextResponse.json(
        { error: "지금은 답변을 확인하기 어렵습니다. 잠시 후 다시 시도해 주세요." },
        { status: 502 },
      );
    }

    const data = (await openAIResponse.json()) as {
      status?: string;
      incomplete_details?: { reason?: string };
      output_text?: string;
      output?: Array<{
        content?: Array<{
          type?: string;
          text?: string;
          annotations?: Array<{ type?: string; url?: string; title?: string }>;
        }>;
      }>;
    };
    const content = data.output?.flatMap((item) => item.content ?? []) ?? [];
    const answer = data.output_text || content.find((item) => item.type === "output_text")?.text;

    if (!answer) {
      console.error(
        "OpenAI response contained no text",
        data.status,
        data.incomplete_details?.reason,
      );
      throw new Error("OpenAI response contained no text");
    }
    const sources = Array.from(
      new Map(
        content
          .flatMap((item) => item.annotations ?? [])
          .filter((item) => item.type === "url_citation" && item.url)
          .map((item) => [item.url as string, item.title || item.url as string]),
      ),
    ).slice(0, 4);
    const sourcedAnswer = sources.length
      ? `${answer}\n\n공식 근거·출처\n${sources.map(([url, title]) => `- ${title}: ${url}`).join("\n")}`
      : answer;
    const plainAnswer = sourcedAnswer.replace(/[#*]/g, "");
    return NextResponse.json({ answer: plainAnswer });
  } catch (error) {
    console.error("Museum answer error", error);
    return NextResponse.json(
      { error: "답변 연결 중 문제가 생겼습니다. 잠시 후 다시 시도해 주세요." },
      { status: 502 },
    );
  }
}
